name: 'actions'
description: 'generic actions'
inputs:
  flags:
    description: 'flags'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://mborejdo/action-e2e'
  args:
    - ${{ inputs.flags }}